apiVersion: v1
kind: Service
metadata:
  name: kube-dns-lb-tcp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: kube-dns
spec:
  selector:
    k8s-app: kube-dns
  type:  LoadBalancer
  loadBalancerIP: 172.16.255.5
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53
