ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "selfsigned"
  hosts:
    - name: chartmuseum.k8s.local
      path: /
      tls: true
      tlsSecret: chartmuseum-tls
 
env:
  open:
    DISABLE_API: false
