apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

## PrefixSuffixTransformer
namePrefix: prod-

## NamespaceTransformer
namespace: hipster-shop-prod 

## LabelTransformer
commonLabels:
  environment: prod
