apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vault-ui
  namespace: vault
spec:
  rules:
  - host: vault.k8s.local
    http:
      paths:
      - path:
        backend:
          serviceName: vault-ui
          servicePort: 8200
