controller:

  # Will add custom configuration options to Nginx
  config:
    log-format-escape-json: "true"
    log-format-upstream: '{"timestamp": "$time_iso8601", 
      "requestID": "$req_id", 
      "proxyUpstreamName": "$proxy_upstream_name",
      "proxyAlternativeUpstreamName": "$proxy_alternative_upstream_name",
      "upstreamStatus": "$upstream_status",
      "upstreamAddr": "$upstream_addr",
      "x-forward-for": "$proxy_add_x_forwarded_for",
      "httpRequest":{"requestMethod": "$request_method", "requestUrl": "$host$request_uri",
      "status": $status,"requestSize": "$request_length", "responseSize": "$upstream_response_length",
      "userAgent": "$http_user_agent", "remoteIp": "$remote_addr", "referer": "$http_referer",
      "latency": "$upstream_response_time s", "protocol":"$server_protocol"}}'

  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"


    serviceMonitor:
      port: 10254
      enabled: true
      additionalLabels: {}
      namespace: ""
      namespaceSelector: {}
      # Default: scrape .Release.Namespace only
      # To scrape all, use the following:
      # namespaceSelector:
      #   any: true
      scrapeInterval: 30s
      # honorLabels: true

       
