apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-shop
  labels:
    app: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
